### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by acaloiaro** [acaloiaro/topk-taupath#2]
I'm sifting through old data and examples from the paper to determine which of the many R implementations are nearest to "canonical". While `TKTP` does not call for a unique tau path -- merely one that is monotonically decreasing -- the results from the paper are from what we considered at the time to be a canonical R implementation. 

The primary issue I'm dealing with now is that R FastBCS was never ideal due to R's performance constraints, and as a result, Java FastBCS became canonical for the purpose of validating FastBCS2 for large vectors, i.e. `(N>4000)`. You can observe that results in the paper for context `FB-RP1s`  (sequential R FastBCS) are missing above `N=4000`; this is due to R's performance characteristics. For large vectors, R was prohibitively non-performant on the hardware we had available. 

All this to say that Java FastBCS and Java FastBCS2 are in a good and working state (producing the same permutation indices/tau paths), but I prefer to maintain my goal of releasing FastBCS R and FastBCS2 R first, as R is a staple of the scientific and statistical communities. This means that I'll need to backport some of the Java implementation to R so that the two can be validated against echo other prior to moving forward implementing FastBCS2 R. For those who are unaware, FastBCS2 R was never implemented. It was only implemented in Java and Swift. 

I want to leave as little as possible of the FastBCS2 R implementation up to my judgement, and I believe the best way to do that is to take a validation-only approach. I do this by comparing the permutation indices returned from implementations. 

I'll proceed with FastBCS Java as canonical; implement a matching FastBCS R; and finally implement FastBCS2 R. It's tedious work, and I would do it more in the open by making my source available, but vanity precludes me from putting some of this code on public display in its current state! 

If you're interested in the work and think you can help, feel free to reach out to me directly and I'm happy to share the source with you. 

CC: @NickCH-K

**Comment by NickCH-K** [comment]
I'd love to help! I don't think I've touched Java since my "Intro to Programming" class however many years ago, but I should be able to read it and translate into R.

**Comment by acaloiaro** [comment]
> I'd love to help! I don't think I've touched Java since my "Intro to Programming" class however many years ago, but I should be able to read it and translate into R.

Thanks for the offer, Nick! I just got very lucky and found the change that resulted in the Java and R implementations producing slightly different paths. I'll start digging through our research notes to determine why the change was made. It has to do with excluding the concordance matrix diagonal from column summation. 

Thankfully, with the combination of Git and a comprehensive digital notes, I should be able to find a conclusive answer.

**Comment by acaloiaro** [comment]
@NickCH-K Everything is validating correctly now. FastBCS R, FastBCS Java, and FastBCS2 Java are now all available. 

You can have a high degree of confidence that FastBCS R is correct per the examples from our paper. 

FastBCS2 R is forthcoming. Cheers!

**Comment by NickCH-K** [comment]
That's awesome! Thanks again so much for putting this together.

**Comment by acaloiaro** [comment]
Instead of implementing FastBCS2 R, I'm considering writing an R wrapper around FastBCS2 Java so it can be used in R. Would you have any opposition to that?

**Comment by NickCH-K** [comment]
No opposition at all! Sounds good to me. I've heard good things about rjava.
